# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - OutSpeech/OutSpeech.psd1

pool:
  vmImage: "windows-2019"

steps:
  - task: PowerShell@2
    displayName: "Run InvokeBuild Tasks"
    inputs:
      filePath: "Build.ps1"
      pwsh: false

  - task: PublishTestResults@2
    displayName: "Publish Pester Test Results"
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "**/TEST-*.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)/TestResults"
      failTaskOnFailedTests: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Pipeline.Workspace)/s/artifacts"
      artifact: "OutSpeech"
      publishLocation: "pipeline"
